# -*- coding: utf-8 -*-
"""Analise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14wToDQKCR3LOpEFihnhgdRBvFBWMD2Ma

# 📈 Lendo a tabela
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Teste/PlanilhaOFC.csv", encoding="ISO-8859-1")
display(df)

"""# 🔍 Informações do DF"""

display(df.info())
print()
display(df.describe())
print()
display(df.count())

"""# Porcentagem de pacientes com e sem problemas."""

qtde_categoria = df["PACIENTE"].value_counts()
display(qtde_categoria)
print()
qtde_categoria_perc = df["PACIENTE"].value_counts(normalize=True).round(2)
display(qtde_categoria_perc)

"""<hr>
<div align="center"><h1>Análise gráfica</h1></div>
<hr>

# 🤚 Mão direita: 🧠 Transtorno mental
"""

import plotly.express as px
fig = px.bar(df, x = "POLEGAR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x = "INDICADOR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MEDIO D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "ANELAR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MINIMO D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

"""# ✋ Mão esquerda: 🧠 Transtorno mental



"""

fig = px.bar(df, x = "PLOEGAR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "INDICADOR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MEDIO E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "ANELAR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MINIMO E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()