# -*- coding: utf-8 -*-
"""Analise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14wToDQKCR3LOpEFihnhgdRBvFBWMD2Ma

# 📈 Lendo a tabela
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Teste/Planilha.csv", encoding="ISO-8859-1")
display(df)

"""# 🔍 Informações do DF"""

display(df.info())
print()
display(df.describe())
print()
display(df.count())

"""# Porcentagem de pacientes com e sem problemas."""

qtde_categoria = df["PACIENTE"].value_counts()
display(qtde_categoria)
print()
qtde_categoria_perc = df["PACIENTE"].value_counts(normalize=True).round(2)
display(qtde_categoria_perc)

"""<div align="center">

---
# ⬇ Análise gráfica ⬇
---

</div>

# 🤚 Mão direita: 👀⛔ Deficiência visual
"""

fig = px.bar(df, x="POLEGAR D", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "DEFICIENCIA VISUAL", barmode="group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: 👀⛔ Deficiência visual"""

fig = px.bar(df, x="PLOEGAR E", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "DEFICIENCIA VISUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# 🤚 Mão direita: 🟢⛔ Daltonismo"""

fig = px.bar(df, x="POLEGAR D", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: 🟢⛔ Daltonismo"""

fig = px.bar(df, x="PLOEGAR E", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "DALTONISMO", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# 🤚 Mão direita: 👂⛔ Deficiência auditiva"""

fig = px.bar(df, x="POLEGAR D", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: 👂⛔ Deficiência auditiva"""

fig = px.bar(df, x="PLOEGAR E", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "DEFICIENCIA AUDITIVA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# 🤚 Mão direita: 🧠 Transtorno mental"""

import plotly.express as px
fig = px.bar(df, x = "POLEGAR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "INDICADOR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MEDIO D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "ANELAR D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MINIMO D", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

"""# ✋ Mão esquerda: 🧠 Transtorno mental"""

fig = px.bar(df, x = "PLOEGAR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "INDICADOR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MEDIO E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "ANELAR E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

fig = px.bar(df, x = "MINIMO E", y = "TRANSTORNO MENTAL", barmode = 'group', color = "PACIENTE")
fig.show()

"""# 🤚 Mão direita: 🧠⛔ Deficiência intelectual"""

fig = px.bar(df, x="POLEGAR D", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: 🧠⛔ Deficiência intelectual"""

fig = px.bar(df, x="PLOEGAR E", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "DEFICIENCIA INTELECTUAL", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# 🤚 Mão direita: 💪⛔ Deficiência motora"""

fig = px.bar(df, x="POLEGAR D", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: 💪⛔ Deficiência motora"""

fig = px.bar(df, x="PLOEGAR E", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "DEFICIENCIA MOTORA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# 🤚 Mão direita: ✍ Escrita"""

fig = px.bar(df, x="POLEGAR D", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR D", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO D", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR D", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO D", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

"""# ✋ Mão esquerda: ✍ Escrita"""

fig = px.bar(df, x="PLOEGAR E", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="INDICADOR E", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MEDIO E", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="ANELAR E", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()

fig = px.bar(df, x="MINIMO E", y = "ESCRITA", barmode = "group", color = "PACIENTE", text_auto=True)
fig.show()